### ISSUE TITLE
Windows 1 click instal error

### ISSUE THREAD

**Issue by krysof** [Sanster/lama-cleaner#190]
[14:37:06] INFO     Load config from config.json                                                             tasks.py:98
           INFO     Using random port: 58448                                                                tasks.py:106
Traceback (most recent call last):
  File "F:\dissfusion\lama-cleaner\installer\Scripts\invoke-script.py", line 10, in <module>
    sys.exit(program.run())
  File "F:\dissfusion\lama-cleaner\installer\lib\site-packages\invoke\program.py", line 384, in run
    self.execute()
  File "F:\dissfusion\lama-cleaner\installer\lib\site-packages\invoke\program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "F:\dissfusion\lama-cleaner\installer\lib\site-packages\invoke\executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "F:\dissfusion\lama-cleaner\installer\lib\site-packages\invoke\tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "F:\dissfusion\lama-cleaner\tasks.py", line 121, in start
    commandline_args = ' '.join(commandline_args)
TypeError: sequence item 5: expected str instance, int found

**Comment by Sanster** [comment]
fixed https://github.com/Sanster/lama-cleaner/commit/00def97e9fc80325069fe0e991822f78f9652fbc
