### ISSUE TITLE
How to update to v1 from One Click Installer

### ISSUE THREAD

**Issue by Tobe2d** [Sanster/lama-cleaner#257]
I run win_config.bat and activated the new plugins however i get this error:
ERROR    | lama_cleaner.plugins.base_plugin:__init__:8 -  RealESRGAN is not installed, please install it first. pip install realesrgan

How to install pip install realesrgan in the same env? to keep things clean as I dont wan to just install those add-ons on the main python.

**Comment by Sanster** [comment]
You can change the corresponding section in win_config.bat to the following lines:

```bash
@call conda install -y -c conda-forge cudatoolkit=11.7
@call pip3  install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
@call pip3 install xformers
@call pip3 install -U lama-cleaner
@call lama-cleaner --install-plugins-package
```

**Comment by Tobe2d** [comment]
Thanks for the reply @Sanster 

I have done that and now when I run win_start.bat I get this error:

```
lama-cleaner: error: torch.cuda.is_available() is False, please use --device cpu or check your pytorch installation
Press any key to continue . . .

```




If you are intersted in the full log here it is:


```
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.6
- torch: 1.13.1
- Pillow: 9.4.0
- diffusers: 0.14.0
- transformers: 4.25.1
- opencv-python: 4.7.0.68
- xformers: 0.0.18
- accelerate: 0.15.0
- lama-cleaner: 1.0.1

2023-04-02 05:45:42.039 | INFO     | lama_cleaner.parse_args:parse_args:169 - Loading installer config from E:\lama-cleaner\win_start.bat\..\installer_config.json
usage: lama-cleaner [-h] [--host HOST] [--port PORT] [--config-installer] [--load-installer-config]
                    [--installer-config INSTALLER_CONFIG]
                    [--model {lama,ldm,zits,mat,fcf,sd1.5,anything4,realisticVision1.4,cv2,manga,sd2,paint_by_example,instruct_pix2pix}]
                    [--no-half] [--cpu-offload] [--disable-nsfw] [--sd-cpu-textencoder] [--sd-controlnet]
                    [--sd-local-model-path SD_LOCAL_MODEL_PATH] [--local-files-only] [--enable-xformers]
                    [--device {cuda,cpu,mps}] [--gui] [--no-gui-auto-close] [--gui-size GUI_SIZE GUI_SIZE]
                    [--input INPUT] [--output-dir OUTPUT_DIR] [--model-dir MODEL_DIR] [--disable-model-switch]
                    [--quality QUALITY] [--enable-interactive-seg] [--enable-remove-bg] [--enable-realesrgan]
                    [--realesrgan-device {cpu,cuda,mps}]
                    [--realesrgan-model {realesr-general-x4v3,RealESRGAN_x4plus,RealESRGAN_x4plus_anime_6B}]
                    [--enable-gfpgan] [--gfpgan-device {cpu,cuda,mps}] [--enable-restoreformer]
                    [--restoreformer-device {cpu,cuda,mps}] [--enable-gif] [--install-plugins-package]
lama-cleaner: error: torch.cuda.is_available() is False, please use --device cpu or check your pytorch installation
Press any key to continue . . .
```

**Comment by Sanster** [comment]
I'm not sure why it has become a cpu version of torch, you can create a new bat file next to win_config and update torch separately

```
@echo off

set PATH=C:\Windows\System32;%PATH%

@call installer\Scripts\activate.bat

@call conda-unpack

@call conda install -y -c conda-forge cudatoolkit=11.7
@call pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
PAUSE
```

**Comment by Tobe2d** [comment]
I created new .bat file and added the code above. When I run it it show this:

```
Traceback (most recent call last):
  File "E:\Ai__Project\lama-cleaner\installer\Scripts\conda-unpack-script.py", line 226, in <module>
    update_prefix(os.path.join(new_prefix, path), new_prefix,
  File "E:\Ai__Project\lama-cleaner\installer\Scripts\conda-unpack-script.py", line 66, in update_prefix
    with open(path, 'rb+') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Ai__Project\\lama-cleaner\\installer\\Library\\bin\\libcrypto-1_1-x64.dll.c~.conda_trash'

```

And now when I run win_start.bat i get this:

![image](https://user-images.githubusercontent.com/4099839/229361461-624c7098-0c6e-472f-9f25-a03bfecf949e.png)


After that it did download few things and start and yes it work ;-)

Howevere, whenever I start win_start.bat i get this:

![image](https://user-images.githubusercontent.com/4099839/229362205-850b9807-a790-485b-bab8-b30cf85b0018.png)

**Comment by Sanster** [comment]
You can create a new bat file next to win_config to fix xformers error
```bash
@echo off

set PATH=C:\Windows\System32;%PATH%

@call installer\Scripts\activate.bat

@call conda-unpack

@call pip3 install xformers==0.0.16

PAUSE
```

The torch becomes the cpu version and the xformer error is due to the installation of xformers==0.0.18 which depend on torch 2.0, I was using an old python pypi source to do test so I didn't find this problem.

**Comment by Tobe2d** [comment]
Maybe new one click installer is the soulution?

**Comment by Sanster** [comment]
There is no need to re-download installer, if you are concerned that the current installer environment is messed up, you can unzip the zip package again and replace the contents of win_config.bat with the following:

```bash
@echo off

set PATH=C:\Windows\System32;%PATH%

@call installer\Scripts\activate.bat

@call conda-unpack

@call conda install -y -c conda-forge cudatoolkit=11.7
@call pip3 install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
@call pip3 install xformers==0.0.16
@call pip3 install -U lama-cleaner
@call lama-cleaner --install-plugins-package

@call lama-cleaner --config-installer --installer-config %0\..\installer_config.json

PAUSE
```

**Comment by Sanster** [comment]
@Gourieff when `--installer-config` is used, all config is load from `installer_config.json`, you can add command line arg in `installer_config.json`

```json
{
    "enable_realesrgan": true,
    "realesrgan_device": "cuda",
    "realesrgan_model": "RealESRGAN_x4plus"
}
```

**Comment by Gourieff** [comment]
> @Gourieff when `--installer-config` is used, all config is load from `installer_config.json`, you can add command line arg in `installer_config.json`
> 
> ```json
> {
>     "enable_realesrgan": true,
>     "realesrgan_device": "cuda",
>     "realesrgan_model": "RealESRGAN_x4plus"
> }
> ```

Thanks a lot 👍🏻 It works great!
All plugins' files were successfully loaded and the plugin button appeared!

**Comment by ffdown** [comment]
> There is no need to re-download installer, if you are concerned that the current installer environment is messed up, you can unzip the zip package again and replace the contents of win_config.bat with the following:
> 
> ```shell
> @echo off
> 
> set PATH=C:\Windows\System32;%PATH%
> 
> @call installer\Scripts\activate.bat
> 
> @call conda-unpack
> 
> @call conda install -y -c conda-forge cudatoolkit=11.7
> @call pip3 install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
> @call pip3 install xformers==0.0.16
> @call pip3 install -U lama-cleaner
> @call lama-cleaner --install-plugins-package
> 
> @call lama-cleaner --config-installer --installer-config %0\..\installer_config.json
> 
> PAUSE
> ```

Best option!
