### ISSUE TITLE
[BUG] All samplers work except for dpm++ on Mac

### ISSUE THREAD

**Issue by alexzadeh** [Sanster/lama-cleaner#294]
**Model**
Stable Diffusion (Realistic Vision 1.4)

**Describe the bug**
All samplers work except for dpm++. When dpm++ is selected, a few seconds after clicking the 'Dream' button I get this error in the app:

> Something went wrong: Error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final/EN" <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <>The server encountered an internal error and was unable to complete vour reauest. Either the server is overloaded or there is an error in the application </n>

I get this print in my shell:
`127.0.0.1 - - [23/Apr/2023 23:37:13] "POST /inpaint HTTP/1.1" 200 -
2023-04-23 23:37:58.727 | INFO     | lama_cleaner.server:process:255 - Origin image shape: (1024, 1024, 3)
2023-04-23 23:37:58.727 | INFO     | lama_cleaner.server:process:257 - Resized image shape: (1024, 1024, 3)
2023-04-23 23:37:58.728 | INFO     | lama_cleaner.model.base:_scaled_pad_forward:276 - Resize image to do sd inpainting: (981, 570, 3) -> (981, 570, 3)
2023-04-23 23:37:58.728 | INFO     | lama_cleaner.model.base:_pad_forward:56 - final forward pad size: (984, 576, 3)
  6%|█████▉                                                                                                    | 1/18 [00:02<00:46,  2.73s/it]
2023-04-23 23:38:02.061 | INFO     | lama_cleaner.server:process:273 - process time: 3333.6896896362305ms
[2023-04-23 23:38:02,062] ERROR in app: Exception on /inpaint [POST]
Traceback (most recent call last):
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/lama_cleaner/server.py", line 263, in process
    res_np_img = model(image, mask, config)
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/lama_cleaner/model_manager.py", line 60, in __call__
    return self.model(image, mask, config)
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/lama_cleaner/model/base.py", line 263, in __call__
    crop_image = self._scaled_pad_forward(crop_img, crop_mask, config)
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/lama_cleaner/model/base.py", line 279, in _scaled_pad_forward
    inpaint_result = self._pad_forward(downsize_image, downsize_mask, config)
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/lama_cleaner/model/base.py", line 58, in _pad_forward
    result = self.forward(pad_image, pad_mask, config)
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/lama_cleaner/model/sd.py", line 143, in forward
    output = self.model(
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py", line 865, in __call__
    latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs).prev_sample
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/diffusers/schedulers/scheduling_dpmsolver_multistep.py", line 475, in step
    prev_sample = self.multistep_dpm_solver_second_order_update(
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/diffusers/schedulers/scheduling_dpmsolver_multistep.py", line 367, in multistep_dpm_solver_second_order_update
    return x_t
UnboundLocalError: local variable 'x_t' referenced before assignment
127.0.0.1 - - [23/Apr/2023 23:38:02] "POST /inpaint HTTP/1.1" 500 -
l__
    latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs).prev_sample
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/diffusers/schedulers/scheduling_dpmsolver_multistep.py", line 475, in step
    prev_sample = self.multistep_dpm_solver_second_order_update(
  File "/Users/Alex/miniconda3/envs/pytorch_env/lib/python3.10/site-packages/diffusers/schedulers/scheduling_dpmsolver_multistep.py", line 367, in multistep_dpm_solver_second_order_update
    return x_t
UnboundLocalError: local variable 'x_t' referenced before assignment
127.0.0.1 - - [23/Apr/2023 23:38:02] "POST /inpaint HTTP/1.1" 500 -`

**System Info**
Software version used
- lama-cleaner: 1.1.2
- pytorch: 2.0.0

I'm using mps on Mac OS 13.3.1

**Comment by Sanster** [comment]
Which version of `diffusers` are you using? I test with diffusers==0.14.0 and it works fine.

**Comment by alexzadeh** [comment]
Hey, I'm on 0.14.0. I just gave it another go, and now it's working. I'm really not sure what has changed! I've rebooted recently, so perhaps that's it. Apologies.
