### ISSUE TITLE
Stable Diffusion install not working after installing: Inpaint Anything for Stable Diffusion Web UI

### ISSUE THREAD

**Issue by mtsweir** [Sanster/lama-cleaner#317]
**Model**
Lama not installed yet.

**Describe the bug**
I followed instructions to install this repo on my local Stable Diffusion installation:
https://github.com/Uminosachi/sd-webui-inpaint-anything

When I run SD it gives me this error message:
```
venv "C:\stable-diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.2.1
Commit hash: 89f9faa63388756314e8a1d96cf86bf5e0663045
Traceback (most recent call last):
  File "C:\stable-diffusion\stable-diffusion-webui\launch.py", line 369, in <module>
    prepare_environment()
  File "C:\stable-diffusion\stable-diffusion-webui\launch.py", line 274, in prepare_environment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "C:\stable-diffusion\stable-diffusion-webui\launch.py", line 135, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "C:\stable-diffusion\stable-diffusion-webui\launch.py", line 111, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "C:\stable-diffusion\stable-diffusion-webui\venv\Scripts\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check


Press any key to continue . . .
```

**Screenshots**
![SD-bug](https://github.com/Sanster/lama-cleaner/assets/4976660/bb34ed63-aba3-4137-912c-a096b55afb9b)

**System Info**
![GF-driver](https://github.com/Sanster/lama-cleaner/assets/4976660/05599148-b89e-4568-aebb-672f6ce3dbad)
Software version used
- lama-cleaner: unsure as can't launch SD
- pytorch: unsure as can't launch SD
- CUDA: unsure as can't launch SD

**Comment by Sanster** [comment]
hi, I'm not sure what operations have been done in https://github.com/Uminosachi/sd-webui-inpaint-anything. Please open an issue in that project.
