### ISSUE TITLE
[BUG] AssertionError on Install

### ISSUE THREAD

**Issue by dumbshow** [Sanster/lama-cleaner#338]
**Model**
N/A?

**Describe the bug**
Unable to install in a fresh virtualenv.

**Screenshots**

`pip install --no-cache-dir lama-cleaner`

```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/martin/Documents/projects/envs/env_lama_cleaner/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/martin/Documents/projects/envs/env_lama_cleaner/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/martin/Documents/projects/envs/env_lama_cleaner/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/home/martin/Documents/projects/envs/env_lama_cleaner/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/home/martin/Documents/projects/envs/env_lama_cleaner/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError
```

**System Info**
Software version used
- Ubuntu 22.04.2 LTS
- lama-cleaner: "Downloading lama_cleaner-1.2.1-py3-none-any.whl (6.8 MB)"
- pytorch:  "Downloading torch-2.0.1-cp310-cp310-manylinux1_x86_64.whl (619.9 MB)"
- CUDA: "Downloading nvidia_cuda_runtime_cu11-11.7.99-py3-none-manylinux1_x86_64.whl (849 kB)"

Thank you!

**Comment by Sanster** [comment]
I'm not sure how to resolve this dependency error, but I suggest you try this command.

```bash
pip install torch==1.13.1+cu117 torchvision==0.14.1 --extra-index-url https://download.pytorch.org/whl/cu117
pip install lama-cleaner
```
