### ISSUE TITLE
[BUG] This is a new bug after a fresh install of pip install lama-cleaner

### ISSUE THREAD

**Issue by jameswan** [Sanster/lama-cleaner#341]
Platform: Windows 64-bit
CUDA 11.7
pip install torch==1.13.1+cu117 torchvision==0.14.1 --extra-index-url https://download.pytorch.org/whl/cu117 --force-reinstall

Bug occurs immediately after masking out something on the image.

[2023-07-09 11:31:28,075] ERROR in app: Exception on /inpaint [POST]
Traceback (most recent call last):
  File "C:\Users\James\anaconda3\envs\lama_cleaner\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\James\anaconda3\envs\lama_cleaner\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\James\anaconda3\envs\lama_cleaner\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\James\anaconda3\envs\lama_cleaner\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\James\anaconda3\envs\lama_cleaner\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\James\anaconda3\envs\lama_cleaner\lib\site-packages\lama_cleaner\server.py", line 241, in process
    config = Config(
  File "C:\Users\James\anaconda3\envs\lama_cleaner\lib\site-packages\pydantic\main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
paint_by_example_example_image
  Input should be an instance of Image [type=is_instance_of, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.1.2/v/is_instance_of
127.0.0.1 - - [09/Jul/2023 11:31:28] "POST /inpaint HTTP/1.1" 500 -

**Comment by jameswan** [comment]
Dupe of previous bug
