### ISSUE TITLE
[BUG] Bug encountered while running the "lama" model and performing inpainting on the input image.

### ISSUE THREAD

**Issue by Nathan-Hou** [Sanster/lama-cleaner#342]
**Model**
Which model are you using?
lama

**Describe the bug**
The installation and execution were successful. When inpainting was performed on the example image "ELDER RING," the following error was reported.
`
[2023-07-09 09:15:26,428] ERROR in app: Exception on /inpaint [POST]
Traceback (most recent call last):
  File "D:\P_Hao\seait_installers_version_0.1.4\lama-cleaner\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\P_Hao\seait_installers_version_0.1.4\lama-cleaner\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\P_Hao\seait_installers_version_0.1.4\lama-cleaner\venv\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\P_Hao\seait_installers_version_0.1.4\lama-cleaner\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\P_Hao\seait_installers_version_0.1.4\lama-cleaner\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\P_Hao\seait_installers_version_0.1.4\lama-cleaner\venv\lib\site-packages\lama_cleaner\server.py", line 241, in process
    config = Config(
  File "D:\P_Hao\seait_installers_version_0.1.4\lama-cleaner\venv\lib\site-packages\pydantic\main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
paint_by_example_example_image
  Input should be an instance of Image [type=is_instance_of, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.1.2/v/is_instance_of
127.0.0.1 - - [09/Jul/2023 09:15:26] "POST /inpaint HTTP/1.1" 500 -
`

**Screenshots**
![lama-test01](https://github.com/Sanster/lama-cleaner/assets/67326186/1528050c-a1f9-42c5-93aa-3f07c49f784c)
![lama-test02](https://github.com/Sanster/lama-cleaner/assets/67326186/e2ebaf12-4813-4ae1-b105-4817e95d778c)

**System Info**
Software version used
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.6
- torch: 1.12.1+cu113
- torchvision: 0.13.1+cu113
- Pillow: 10.0.0
- diffusers: 0.16.1
- transformers: 4.27.4
- opencv-python: 4.8.0.74
- xformers: N/A
- accelerate: N/A
- lama-cleaner: 1.2.1
- rembg: N/A
- realesrgan: N/A
- gfpgan: N/A

**Comment by Sanster** [comment]
This bug has been fixed in version 1.2.2, please update to 1.2.2

**Comment by Nathan-Hou** [comment]
Thanks. It works.
