### ISSUE TITLE
1 Click Installer : AttributeError: 'LaMa' object has no attribute 'is_local_sd_model'

### ISSUE THREAD

**Issue by Acephalia** [Sanster/lama-cleaner#348]
I was using the cleaner fine but when I tried to boot it up today it throws this error on all models. Ran config to see if there were any updates but no luck. Some help would be appreciated. 

```
[2023-07-18 17:13:08,790] ERROR in app: Exception on /inpaint [POST]
Traceback (most recent call last):
  File "S:\lama-cleaner\installer\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "S:\lama-cleaner\installer\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "S:\lama-cleaner\installer\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "S:\lama-cleaner\installer\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "S:\lama-cleaner\installer\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "S:\lama-cleaner\installer\lib\site-packages\lama_cleaner\server.py", line 291, in process
    res_np_img = model(image, mask, config)
  File "S:\lama-cleaner\installer\lib\site-packages\lama_cleaner\model_manager.py", line 63, in __call__
    self.switch_controlnet_method(control_method=config.controlnet_method)
  File "S:\lama-cleaner\installer\lib\site-packages\lama_cleaner\model_manager.py", line 88, in switch_controlnet_method
    if self.model.is_local_sd_model:
AttributeError: 'LaMa' object has no attribute 'is_local_sd_model'
127.0.0.1 - - [18/Jul/2023 17:13:08] "POST /inpaint HTTP/1.1" 500 -
```

**Comment by Sanster** [comment]
fixed in 1.2.3
