### ISSUE TITLE
[BUG] fastapi AttributeError: 'FieldInfo' object has no attribute 'in_'

### ISSUE THREAD

**Issue by clementvp** [Sanster/lama-cleaner#353]
**Model**
Windows last model
**Describe the bug**
When launching windows installer it's get an install error.

**Screenshots**

**System Info**
Software version used
- lama-cleaner: latest ( 07/25/23)
- windows 10

When installing on windows, launching the config.bat get this error:  
```
2023-07-25 20:58:46.503 | INFO     | lama_cleaner.parse_args:parse_args:185 - Launching installer web config page
Traceback (most recent call last):
  File "C:\Users\cleme\Desktop\eb779892-012a-4435-912c-12d59fa2f587\lama-cleaner\installer\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\cleme\Desktop\eb779892-012a-4435-912c-12d59fa2f587\lama-cleaner\installer\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\cleme\Desktop\eb779892-012a-4435-912c-12d59fa2f587\lama-cleaner\installer\Scripts\lama-cleaner.exe\__main__.py", line 7, in <module>
  File "C:\Users\cleme\Desktop\eb779892-012a-4435-912c-12d59fa2f587\lama-cleaner\installer\lib\site-packages\lama_cleaner\__init__.py", line 13, in entry_point
    args = parse_args()
  File "C:\Users\cleme\Desktop\eb779892-012a-4435-912c-12d59fa2f587\lama-cleaner\installer\lib\site-packages\lama_cleaner\parse_args.py", line 186, in parse_args
    main(args.installer_config)
  File "C:\Users\cleme\Desktop\eb779892-012a-4435-912c-12d59fa2f587\lama-cleaner\installer\lib\site-packages\lama_cleaner\web_config.py", line 77, in main
    with gr.Blocks() as demo:
  File "C:\Users\cleme\Desktop\eb779892-012a-4435-912c-12d59fa2f587\lama-cleaner\installer\lib\site-packages\gradio\blocks.py", line 1478, in __exit__
    self.app = routes.App.create_app(self)
  File "C:\Users\cleme\Desktop\eb779892-012a-4435-912c-12d59fa2f587\lama-cleaner\installer\lib\site-packages\gradio\routes.py", line 220, in create_app
    def login(form_data: OAuth2PasswordRequestForm = Depends()):
  File "C:\Users\cleme\Desktop\eb779892-012a-4435-912c-12d59fa2f587\lama-cleaner\installer\lib\site-packages\fastapi\routing.py", line 706, in decorator
    self.add_api_route(
  File "C:\Users\cleme\Desktop\eb779892-012a-4435-912c-12d59fa2f587\lama-cleaner\installer\lib\site-packages\fastapi\routing.py", line 645, in add_api_route
    route = route_class(
  File "C:\Users\cleme\Desktop\eb779892-012a-4435-912c-12d59fa2f587\lama-cleaner\installer\lib\site-packages\fastapi\routing.py", line 491, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "C:\Users\cleme\Desktop\eb779892-012a-4435-912c-12d59fa2f587\lama-cleaner\installer\lib\site-packages\fastapi\dependencies\utils.py", line 268, in get_dependant
    sub_dependant = get_param_sub_dependant(
  File "C:\Users\cleme\Desktop\eb779892-012a-4435-912c-12d59fa2f587\lama-cleaner\installer\lib\site-packages\fastapi\dependencies\utils.py", line 111, in get_param_sub_dependant
    return get_sub_dependant(
  File "C:\Users\cleme\Desktop\eb779892-012a-4435-912c-12d59fa2f587\lama-cleaner\installer\lib\site-packages\fastapi\dependencies\utils.py", line 147, in get_sub_dependant
    sub_dependant = get_dependant(
  File "C:\Users\cleme\Desktop\eb779892-012a-4435-912c-12d59fa2f587\lama-cleaner\installer\lib\site-packages\fastapi\dependencies\utils.py", line 289, in get_dependant
    add_param_to_fields(field=param_field, dependant=dependant)
  File "C:\Users\cleme\Desktop\eb779892-012a-4435-912c-12d59fa2f587\lama-cleaner\installer\lib\site-packages\fastapi\dependencies\utils.py", line 462, in add_param_to_fields
    if field_info.in_ == params.ParamTypes.path:
AttributeError: 'FieldInfo' object has no attribute 'in_'
Appuyez sur une touche pour continuer...
```

**Comment by clementvp** [comment]
It's the lama-cleaner --config-installer --installer-config %0\..\installer_config.json command who failed, even in a new conda env ( python 3.10)

**Comment by Sanster** [comment]
Thank you for your report. It seems to be a bug in pydantic. I have found a relevant issue at https://github.com/tiangolo/fastapi/discussions/9942.

Upgrading pydantic to version 2.1.1 should fix it.

**Comment by clementvp** [comment]
Same error with pydantic  2.1.1 installed before the `lama-cleaner --config-installer --installer-config %0\..\installer_config.json `command  

`pip install -U pydantic` ( i see 2.1.1 version)
`lama-cleaner --config-installer --installer-config %0\..\installer_config.json`

same error: 
`Traceback (most recent call last):
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python310\Scripts\lama-cleaner.exe\__main__.py", line 7, in <module>
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python310\lib\site-packages\lama_cleaner\__init__.py", line 13, in entry_point
    args = parse_args()
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python310\lib\site-packages\lama_cleaner\parse_args.py", line 186, in parse_args
    main(args.installer_config)
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python310\lib\site-packages\lama_cleaner\web_config.py", line 77, in main
    with gr.Blocks() as demo:
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1478, in __exit__
    self.app = routes.App.create_app(self)
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 220, in create_app
    def login(form_data: OAuth2PasswordRequestForm = Depends()):
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 706, in decorator
    self.add_api_route(
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 645, in add_api_route
    route = route_class(
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 491, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\dependencies\utils.py", line 268, in get_dependant
    sub_dependant = get_param_sub_dependant(
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\dependencies\utils.py", line 111, in get_param_sub_dependant
    return get_sub_dependant(
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\dependencies\utils.py", line 147, in get_sub_dependant
    sub_dependant = get_dependant(
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\dependencies\utils.py", line 289, in get_dependant
    add_param_to_fields(field=param_field, dependant=dependant)
  File "C:\Users\cleme\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\dependencies\utils.py", line 462, in add_param_to_fields
    if field_info.in_ == params.ParamTypes.path:
AttributeError: 'FieldInfo' object has no attribute 'in_'
Appuyez sur une touche pour continuer...`

I'm in the installer conda env python 3.10

**Comment by clementvp** [comment]
allright, after a new fresh install everything works again, very weird. Maybe requirements point now to the latest version of pydantic (2.1.1 of 07/26/23). Closing.
