### ISSUE TITLE
[BUG] can't switch model, lama-cleaner v3.1

### ISSUE THREAD

**Issue by mitsuke-code** [Sanster/lama-cleaner#354]
Help, i'm using lama-cleaner v3.1, the v1 was working fine when switch model.

Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:
```
pip install accelerate
```
.
[2023-07-27 20:02:45,197] ERROR in app: Exception on /model [POST]
Traceback (most recent call last):
  File "D:\lama-cleaner-main\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\lama-cleaner-main\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\lama-cleaner-main\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\lama-cleaner-main\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\lama-cleaner-main\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\lama-cleaner-main\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\lama_cleaner\server.py", line 452, in switch_model
    model.switch(new_name)
  File "D:\lama-cleaner-main\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\lama_cleaner\model_manager.py", line 76, in switch
    self.model = self.init_model(
  File "D:\lama-cleaner-main\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\lama_cleaner\model_manager.py", line 48, in init_model
    return ControlNet(device, **{**kwargs, "name": name})
  File "D:\lama-cleaner-main\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\lama_cleaner\model\base.py", line 32, in __init__
    self.init_model(device, **kwargs)
  File "D:\lama-cleaner-main\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\lama_cleaner\model\controlnet.py", line 166, in init_model
    self.model = PipeClass.from_pretrained(
  File "D:\lama-cleaner-main\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 884, in from_pretrained
    cached_folder = cls.download(
  File "D:\lama-cleaner-main\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1333, in download
    cached_folder = snapshot_download(
  File "D:\lama-cleaner-main\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\lama-cleaner-main\lama-cleaner-win-v3.1\lama-cleaner\installer\lib\site-packages\huggingface_hub\_snapshot_download.py", line 169, in snapshot_download
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Acer\\.cache\\huggingface\\hub\\models--SG161222--Realistic_Vision_V1.4\\refs\\main'
127.0.0.1 - - [27/Jul/2023 20:02:45] "POST /model HTTP/1.1" 500 -

**Comment by Sanster** [comment]
This is a good suggestion, perhaps in the next version I can add `accelerate` as a dependency.

The new version adds ControlNet on top of the SD model and some of the logic becomes more complex, I was wondering if you are switching models with sd_controlnet enabled and sd_controlnet_method=='control_v11p_sd15_inpaint'? Or can you share your installer_config.json file to help me locate the issue

**Comment by mitsuke-code** [comment]
{
    "host": "127.0.0.1",
    "port": 8080,
    "model": "lama",
    "sd_local_model_path": "",
    "sd_controlnet": true,
    "sd_controlnet_method": "control_v11p_sd15_inpaint",
    "device": "cuda",
    "gui": false,
    "no_gui_auto_close": true,
    "no_half": true,
    "cpu_offload": false,
    "disable_nsfw": true,
    "sd_cpu_textencoder": false,
    "enable_xformers": true,
    "local_files_only": true,
    "model_dir": "C:\\Users\\Acer\\.cache",
    "input": "",
    "output_dir": "",
    "enable_interactive_seg": true,
    "interactive_seg_model": "vit_h",
    "interactive_seg_device": "cpu",
    "enable_remove_bg": false,
    "enable_anime_seg": false,
    "enable_realesrgan": false,
    "realesrgan_device": "cuda",
    "realesrgan_model": "RealESRGAN_x4plus",
    "realesrgan_no_half": false,
    "enable_gfpgan": false,
    "gfpgan_device": "cpu",
    "enable_restoreformer": false,
    "restoreformer_device": "cpu",
    "enable_gif": false
}

**Comment by Sanster** [comment]
As I suspected, currently there isn't a straightforward solution. You can try changing the `model` in the configuration to `realisticVision1.4`, which will allow lama-cleaner to automatically download the model during startup. This way, you should be able to switch it on the web page next time.
