### ISSUE TITLE
[BUG] Cannot apply masks

### ISSUE THREAD

**Issue by Troceleng** [Sanster/lama-cleaner#355]
**Model**
Llama

**Describe the bug**
I wanted to try the new version. The program installs and starts fine. When I apply a mask, I get this error:

[2023-07-28 07:42:29,760] ERROR in app: Exception on /inpaint [POST]
Traceback (most recent call last):
  File "C:\Users\Troc\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Troc\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Troc\AppData\Roaming\Python\Python311\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Troc\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Troc\AppData\Roaming\Python\Python311\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\PORTABLE_SOFTWARE\AI\lama-cleaner-1.2.0\lama_cleaner\server.py", line 232, in process
    config = Config(
             ^^^^^^^
  File "C:\Users\Troc\AppData\Roaming\Python\Python311\site-packages\pydantic\main.py", line 159, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
paint_by_example_example_image
  Input should be an instance of Image [type=is_instance_of, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.1/v/is_instance_of
127.0.0.1 - - [28/Jul/2023 07:42:29] "POST /inpaint HTTP/1.1" 500 -

**System Info**
Software version used
- lama-cleaner: 1.2.0
- pytorch: 2.0.1 stable
- CUDA: 12.1

**Comment by Sanster** [comment]
This has already been installed in the new version, please upgrade to the new version 1.2.3

**Comment by Troceleng** [comment]
> This has already been installed in the new version, please upgrade to the new version 1.2.3

But 1.2.0 is the latest I found? Please link 1.2.3.

**Comment by Sanster** [comment]
`pip install lama-cleaner==1.2.3`
