### ISSUE TITLE
[BUG] Lama-cleaner 1 click install for windows

### ISSUE THREAD

**Issue by Gazgiza** [Sanster/lama-cleaner#378]
**Model**
Lama-cleaner one click install on windows

**Describe the bug**
Fatal error in launcher: Unable to create process using '"E:\lama-cleaner\lama-cleaner\installer\python.exe"  "D:\lama-cleaner\lama-cleaner\installer\Scripts\lama-cleaner.exe" --config-installer --installer-config "D:\lama-cleaner\lama-cleaner\win_config.bat"\..\installer_config.json': Le fichier spÚcifiÚ est introuvable.

**Screenshots**

**System Info**
Software version used
- lama-cleaner: lastest
- pytorch: idk
- CUDA: lastest

**Comment by Gazgiza** [comment]
Traceback (most recent call last):
  File "D:\lama-cleaner\lama-cleaner\installer\Scripts\conda-unpack-script.py", line 226, in <module>
    update_prefix(os.path.join(new_prefix, path), new_prefix,
  File "D:\lama-cleaner\lama-cleaner\installer\Scripts\conda-unpack-script.py", line 66, in update_prefix
    with open(path, 'rb+') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\lama-cleaner\\lama-cleaner\\installer\\Library\\bin\\libcrypto-1_1-x64.dll.c~.conda_trash'
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
Requirement already satisfied: torch==1.13.1+cu117 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (1.13.1+cu117)
Requirement already satisfied: torchvision==0.14.1+cu117 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (0.14.1+cu117)
Requirement already satisfied: typing-extensions in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from torch==1.13.1+cu117) (4.7.1)
Requirement already satisfied: requests in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from torchvision==0.14.1+cu117) (2.28.1)
Requirement already satisfied: numpy in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from torchvision==0.14.1+cu117) (1.24.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from torchvision==0.14.1+cu117) (10.0.0)
Requirement already satisfied: charset-normalizer<3,>=2 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from requests->torchvision==0.14.1+cu117) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from requests->torchvision==0.14.1+cu117) (1.26.12)
Requirement already satisfied: idna<4,>=2.5 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from requests->torchvision==0.14.1+cu117) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from requests->torchvision==0.14.1+cu117) (2023.7.22)
Requirement already satisfied: xformers==0.0.16 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (0.0.16)
Requirement already satisfied: torch==1.13.1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from xformers==0.0.16) (1.13.1+cu117)
Requirement already satisfied: numpy in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from xformers==0.0.16) (1.24.4)
Requirement already satisfied: pyre-extensions==0.0.23 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from xformers==0.0.16) (0.0.23)
Requirement already satisfied: typing-inspect in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from pyre-extensions==0.0.23->xformers==0.0.16) (0.9.0)
Requirement already satisfied: typing-extensions in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from pyre-extensions==0.0.23->xformers==0.0.16) (4.7.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from typing-inspect->pyre-extensions==0.0.23->xformers==0.0.16) (1.0.0)
Requirement already satisfied: lama-cleaner in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (1.2.3)
Requirement already satisfied: yacs in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (0.1.8)
Requirement already satisfied: safetensors in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (0.3.2)
Requirement already satisfied: gradio in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (3.40.1)
Requirement already satisfied: controlnet-aux==0.0.3 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (0.0.3)
Requirement already satisfied: flask-socketio in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (5.3.5)
Requirement already satisfied: loguru in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (0.7.0)
Requirement already satisfied: diffusers==0.16.1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (0.16.1)
Requirement already satisfied: flask==2.2.3 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (2.2.3)
Requirement already satisfied: omegaconf in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (2.3.0)
Requirement already satisfied: piexif==1.1.3 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (1.1.3)
Requirement already satisfied: pydantic in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (2.2.1)
Requirement already satisfied: flaskwebgui==0.3.5 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (0.3.5)
Requirement already satisfied: rich in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (12.5.1)
Requirement already satisfied: opencv-python in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (4.8.0.76)
Requirement already satisfied: flask-cors in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (4.0.0)
Requirement already satisfied: torch>=1.9.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (1.13.1+cu117)
Requirement already satisfied: transformers==4.27.4 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (4.27.4)
Requirement already satisfied: simple-websocket in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from lama-cleaner) (0.10.1)
Requirement already satisfied: einops in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (0.6.1)
Requirement already satisfied: huggingface-hub in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (0.16.4)
Requirement already satisfied: filelock in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (3.12.2)
Requirement already satisfied: torchvision in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (0.14.1+cu117)
Requirement already satisfied: Pillow in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (10.0.0)
Requirement already satisfied: scikit-image in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (0.21.0)
Requirement already satisfied: importlib-metadata in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (6.8.0)
Requirement already satisfied: scipy in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (1.11.2)
Requirement already satisfied: timm in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (0.9.5)
Requirement already satisfied: numpy in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (1.24.4)
Requirement already satisfied: regex!=2019.12.17 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from diffusers==0.16.1->lama-cleaner) (2023.8.8)
Requirement already satisfied: requests in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from diffusers==0.16.1->lama-cleaner) (2.28.1)
Requirement already satisfied: Werkzeug>=2.2.2 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from flask==2.2.3->lama-cleaner) (2.3.7)
Requirement already satisfied: Jinja2>=3.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from flask==2.2.3->lama-cleaner) (3.1.2)
Requirement already satisfied: click>=8.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from flask==2.2.3->lama-cleaner) (8.1.7)
Requirement already satisfied: itsdangerous>=2.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from flask==2.2.3->lama-cleaner) (2.1.2)
Requirement already satisfied: whichcraft in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from flaskwebgui==0.3.5->lama-cleaner) (0.6.1)
Requirement already satisfied: pyyaml>=5.1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from transformers==4.27.4->lama-cleaner) (6.0.1)
Requirement already satisfied: tqdm>=4.27 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from transformers==4.27.4->lama-cleaner) (4.64.1)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from transformers==4.27.4->lama-cleaner) (0.13.3)
Requirement already satisfied: packaging>=20.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from transformers==4.27.4->lama-cleaner) (23.1)
Requirement already satisfied: typing-extensions in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from torch>=1.9.0->lama-cleaner) (4.7.1)
Requirement already satisfied: python-socketio>=5.0.2 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from flask-socketio->lama-cleaner) (5.8.0)
Requirement already satisfied: orjson~=3.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (3.9.5)
Requirement already satisfied: altair<6.0,>=4.2.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (5.0.1)
Requirement already satisfied: httpx in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (0.24.1)
Requirement already satisfied: ffmpy in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (0.3.1)
Requirement already satisfied: importlib-resources<7.0,>=1.3 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (6.0.1)
Requirement already satisfied: uvicorn>=0.14.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (0.23.2)
Requirement already satisfied: fastapi in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (0.101.1)
Requirement already satisfied: pandas<3.0,>=1.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (2.0.3)
Requirement already satisfied: markdown-it-py[linkify]>=2.0.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (2.2.0)
Requirement already satisfied: mdit-py-plugins<=0.3.3 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (0.3.3)
Requirement already satisfied: gradio-client>=0.4.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (0.4.0)
Requirement already satisfied: aiofiles<24.0,>=22.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (23.2.1)
Requirement already satisfied: aiohttp~=3.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (3.8.5)
Requirement already satisfied: python-multipart in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (0.0.6)
Requirement already satisfied: websockets<12.0,>=10.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (11.0.3)
Requirement already satisfied: markupsafe~=2.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (2.1.3)
Requirement already satisfied: semantic-version~=2.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (2.10.0)
Requirement already satisfied: pydub in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (0.25.1)
Requirement already satisfied: matplotlib~=3.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio->lama-cleaner) (3.7.2)
Requirement already satisfied: pydantic-core==2.6.1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from pydantic->lama-cleaner) (2.6.1)
Requirement already satisfied: annotated-types>=0.4.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from pydantic->lama-cleaner) (0.5.0)
Requirement already satisfied: win32-setctime>=1.0.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from loguru->lama-cleaner) (1.1.0)
Requirement already satisfied: colorama>=0.3.4 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from loguru->lama-cleaner) (0.4.5)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from omegaconf->lama-cleaner) (4.9.3)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from rich->lama-cleaner) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from rich->lama-cleaner) (2.11.2)
Requirement already satisfied: wsproto in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from simple-websocket->lama-cleaner) (1.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from aiohttp~=3.0->gradio->lama-cleaner) (1.9.2)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from aiohttp~=3.0->gradio->lama-cleaner) (2.0.4)
Requirement already satisfied: frozenlist>=1.1.1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from aiohttp~=3.0->gradio->lama-cleaner) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from aiohttp~=3.0->gradio->lama-cleaner) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from aiohttp~=3.0->gradio->lama-cleaner) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from aiohttp~=3.0->gradio->lama-cleaner) (4.0.3)
Requirement already satisfied: aiosignal>=1.1.2 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from aiohttp~=3.0->gradio->lama-cleaner) (1.3.1)
Requirement already satisfied: toolz in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from altair<6.0,>=4.2.0->gradio->lama-cleaner) (0.11.2)
Requirement already satisfied: jsonschema>=3.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from altair<6.0,>=4.2.0->gradio->lama-cleaner) (4.19.0)
Requirement already satisfied: fsspec in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from gradio-client>=0.4.0->gradio->lama-cleaner) (2023.6.0)
Requirement already satisfied: mdurl~=0.1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from markdown-it-py[linkify]>=2.0.0->gradio->lama-cleaner) (0.1.2)
Requirement already satisfied: linkify-it-py<3,>=1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from markdown-it-py[linkify]>=2.0.0->gradio->lama-cleaner) (2.0.2)
Requirement already satisfied: python-dateutil>=2.7 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from matplotlib~=3.0->gradio->lama-cleaner) (2.8.2)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from matplotlib~=3.0->gradio->lama-cleaner) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from matplotlib~=3.0->gradio->lama-cleaner) (4.42.0)
Requirement already satisfied: cycler>=0.10 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from matplotlib~=3.0->gradio->lama-cleaner) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from matplotlib~=3.0->gradio->lama-cleaner) (1.4.4)
Requirement already satisfied: contourpy>=1.0.1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from matplotlib~=3.0->gradio->lama-cleaner) (1.1.0)
Requirement already satisfied: pytz>=2020.1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from pandas<3.0,>=1.0->gradio->lama-cleaner) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from pandas<3.0,>=1.0->gradio->lama-cleaner) (2023.3)
Requirement already satisfied: python-engineio>=4.3.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from python-socketio>=5.0.2->flask-socketio->lama-cleaner) (4.5.1)
Requirement already satisfied: bidict>=0.21.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from python-socketio>=5.0.2->flask-socketio->lama-cleaner) (0.22.1)
Requirement already satisfied: certifi>=2017.4.17 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from requests->diffusers==0.16.1->lama-cleaner) (2023.7.22)
Requirement already satisfied: idna<4,>=2.5 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from requests->diffusers==0.16.1->lama-cleaner) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from requests->diffusers==0.16.1->lama-cleaner) (1.26.12)
Requirement already satisfied: h11>=0.8 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from uvicorn>=0.14.0->gradio->lama-cleaner) (0.14.0)
Requirement already satisfied: starlette<0.28.0,>=0.27.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from fastapi->gradio->lama-cleaner) (0.27.0)
Requirement already satisfied: sniffio in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from httpx->gradio->lama-cleaner) (1.3.0)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from httpx->gradio->lama-cleaner) (0.17.3)
Requirement already satisfied: zipp>=0.5 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from importlib-metadata->controlnet-aux==0.0.3->lama-cleaner) (3.16.2)
Requirement already satisfied: tifffile>=2022.8.12 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from scikit-image->controlnet-aux==0.0.3->lama-cleaner) (2023.8.12)
Requirement already satisfied: lazy_loader>=0.2 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from scikit-image->controlnet-aux==0.0.3->lama-cleaner) (0.3)
Requirement already satisfied: imageio>=2.27 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from scikit-image->controlnet-aux==0.0.3->lama-cleaner) (2.31.1)
Requirement already satisfied: networkx>=2.8 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from scikit-image->controlnet-aux==0.0.3->lama-cleaner) (3.1)
Requirement already satisfied: PyWavelets>=1.1.1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from scikit-image->controlnet-aux==0.0.3->lama-cleaner) (1.4.1)
Requirement already satisfied: anyio<5.0,>=3.0 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx->gradio->lama-cleaner) (3.7.1)
Requirement already satisfied: referencing>=0.28.4 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio->lama-cleaner) (0.30.2)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio->lama-cleaner) (2023.7.1)
Requirement already satisfied: rpds-py>=0.7.1 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio->lama-cleaner) (0.9.2)
Requirement already satisfied: uc-micro-py in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from linkify-it-py<3,>=1->markdown-it-py[linkify]>=2.0.0->gradio->lama-cleaner) (1.0.2)
Requirement already satisfied: six>=1.5 in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from python-dateutil>=2.7->matplotlib~=3.0->gradio->lama-cleaner) (1.16.0)
Requirement already satisfied: exceptiongroup in d:\lama-cleaner\lama-cleaner\installer\lib\site-packages (from anyio<5.0,>=3.0->httpcore<0.18.0,>=0.15.0->httpx->gradio->lama-cleaner) (1.1.3)
Fatal error in launcher: Unable to create process using '"E:\lama-cleaner\lama-cleaner\installer\python.exe"  "D:\lama-cleaner\lama-cleaner\installer\Scripts\lama-cleaner.exe" --install-plugins-package': Le fichier spÚcifiÚ est introuvable.

Fatal error in launcher: Unable to create process using '"E:\lama-cleaner\lama-cleaner\installer\python.exe"  "D:\lama-cleaner\lama-cleaner\installer\Scripts\lama-cleaner.exe" --config-installer --installer-config "D:\lama-cleaner\lama-cleaner\win_config.bat"\..\installer_config.json': Le fichier spÚcifiÚ est introuvable.

Appuyez sur une touche pour continuer...

**Comment by Gazgiza** [comment]
C:\Users\mine->pip install torch==1.13.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cu117 (from versions: 2.0.0, 2.0.0+cu117, 2.0.1, 2.0.1+cu117)
ERROR: No matching distribution found for torch==1.13.1+cu117

**Comment by Sanster** [comment]
<img width="797" alt="image" src="https://github.com/Sanster/lama-cleaner/assets/3998421/01fc48eb-45f0-491d-a169-d4327d8d5d6b">

Hi, based on this error, did you first unzip it on the E drive and then move it to the D drive? This might cause problems, could you try unzipping the zip package directly on the D drive?

**Comment by blueJYZ** [comment]
> <img alt="image" width="797" src="https://private-user-images.githubusercontent.com/3998421/270166962-01fc48eb-45f0-491d-a169-d4327d8d5d6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NTY2NTksIm5iZiI6MTcyODQ1NjM1OSwicGF0aCI6Ii8zOTk4NDIxLzI3MDE2Njk2Mi0wMWZjNDhlYi00NWYwLTQ5MWQtYTE2OS1kNDMyN2Q4ZDVkNmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDlUMDY0NTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzZiZjZlMjljOGMyNjNhNDEyNmIzNTU3ZDhiZmVhMTEzNGJiMjAwNjQ2YmRmMWJlNzU2YjJmMzhjZDcxNjMxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Pc_7QG-waSQgwhMb-Xe7adSJ3cCBOt-0xq9CVoRFbmQ">
> Hi, based on this error, did you first unzip it on the E drive and then move it to the D drive? This might cause problems, could you try unzipping the zip package directly on the D drive?

if move how relix it>
