### ISSUE TITLE
[BUG] Beta 10 - '500 Internal Server Error' if offline and switching to manually saved .safetensor inpaint model

### ISSUE THREAD

**Issue by TFWol** [Sanster/lama-cleaner#438]
**Model**
Any .safetensor inpaint model not downloaded by the program

**Describe the bug**
If offline and attempting to switch to an inpaint model .safetensor file the program has not downloaded itself, a `500 Internal Server Error` occurs.

Going online makes it work temporarily, but reopening the program offline breaks it again.
Same error whether or not `--local-files-only` is included.

Example commands used:
```cmd
iopaint start --device cuda --interactive-seg-device cuda --enable-remove-bg --enable-interactive-seg --enable-anime-seg --enable-realesrgan --realesrgan-device cuda --enable-gfpgan --gfpgan-device cuda --enable-restoreformer --restoreformer-device cuda --local-files-only
```
```cmd
iopaint start --device cuda --interactive-seg-device cuda --enable-remove-bg --enable-interactive-seg --enable-anime-seg --enable-realesrgan --realesrgan-device cuda --enable-gfpgan --gfpgan-device cuda --enable-restoreformer --restoreformer-device cuda
```

Attempting to use RealisticVision offline
```
2024-01-27 22:59:56.653 | INFO     | iopaint.model_manager:init_model:39 - Loading model: realisticVisionV60B1_v60B1InpaintingVAE.safetensors
2024-01-27 22:59:56.793 | INFO     | iopaint.model_manager:switch:119 - Switch model from lama to realisticVisionV60B1_v60B1InpaintingVAE.safetensors failed, rollback
2024-01-27 22:59:56.794 | INFO     | iopaint.model_manager:init_model:39 - Loading model: lama
2024-01-27 22:59:56.797 | INFO     | iopaint.helper:load_jit_model:104 - Loading model from: C:\Users\user\.cache\torch\hub\checkpoints\big-lama.pt
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\streams\memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\streams\memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\streams\memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\iopaint\api.py", line 108, in exception_handling
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 70, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 299, in app
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\concurrency.py", line 35, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\iopaint\api.py", line 187, in api_switch_model
    self.model_manager.switch(req.name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\iopaint\model_manager.py", line 123, in switch
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\iopaint\model_manager.py", line 113, in switch
    self.model = self.init_model(
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\iopaint\model_manager.py", line 62, in init_model
    return SD(device, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\iopaint\model\base.py", line 279, in __init__
    super().__init__(device, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\iopaint\model\base.py", line 35, in __init__
    self.init_model(device, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\iopaint\model\sd.py", line 50, in init_model
    self.model = StableDiffusionInpaintPipeline.from_single_file(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\diffusers\loaders\single_file.py", line 263, in from_single_file
    pipe = download_from_original_stable_diffusion_ckpt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1319, in download_from_original_stable_diffusion_ckpt
    original_config_file = BytesIO(requests.get(config_url).content)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000226BC8F88D0>: Failed to establish a new connection: [WinError 10049] The requested address is not valid in its context'))
INFO:     127.0.0.1:60836 - "POST /api/v1/model HTTP/1.1" 500 Internal Server Error
```

Using Online - works until you reopen the program offline. It shouldn't be downloading anything.
```
2024-01-27 23:09:34.455 | INFO     | iopaint.model_manager:init_model:39 - Loading model: realisticVisionV60B1_v60B1InpaintingVAE.safetensors
config.json: 100%|████████████████████████████████████████████████████████████████████████| 4.55k/4.55k [00:00<?, ?B/s]
pytorch_model.bin: 100%|██████████████████████████████████████████████████████████| 1.22G/1.22G [00:19<00:00, 63.5MB/s]
preprocessor_config.json: 100%|████████████████████████████████████████████████████████| 342/342 [00:00<00:00, 684kB/s]
C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
INFO:     127.0.0.1:60880 - "POST /api/v1/model HTTP/1.1" 200 OK
```

**System Info**
Software version used
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.11.5
- torch: 2.1.2+cu121
- torchvision: 0.16.2+cu121
- Pillow: 9.5.0
- diffusers: 0.25.1
- transformers: 4.37.0
- opencv-python: 4.9.0.80
- accelerate: 0.26.1
- iopaint: 1.0.0b10
- rembg: 2.0.53
- realesrgan: 0.3.0
- gfpgan: 1.3.8

**Comment by Sanster** [comment]
When loading an SD model from a single file (ckpt/safetensors), even with the `--local-files-only` option, diffusers still downloads the original configuration file: https://raw.githubusercontent.com/CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml.

I have added these configuration files to the iopaint project, and it should already be fixed in `iopaint==1.0.0b11`.

Why load from single file `realisticVisionV60B1_v60B1InpaintingVAE.safetensors` still download some model: Because this file does not include text_encoder, after downloading it once, it should not need to be downloaded again when using other single file files.

**Comment by TFWol** [comment]
Thanks for the explanation, Beta 11 fixed the issue I was having.
