### ISSUE TITLE
Error: IndexError: index 1000 is out of bounds for dimension 0 with size 1000

### ISSUE THREAD

**Issue by DillFrescott** [Sanster/lama-cleaner#53]
IndexError: index 1000 is out of bounds for dimension 0 with size 1000

**Comment by Sanster** [comment]
Can you post the call stack of the error and help me locate the problem?

**Comment by DillFrescott** [comment]
I restarted the server and it seems to have fixed it? At least for lama mode, I'm trying ldm mode right now and will let you know if it wasnt just a one time thing

**Comment by DillFrescott** [comment]
[2022-06-27 02:01:54,912] ERROR in app: Exception on /inpaint [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/lama_cleaner/server.py", line 111, in process
    res_np_img = model(image, mask, config)
  File "/usr/local/lib/python3.7/dist-packages/lama_cleaner/model_manager.py", line 33, in __call__
    return self.model(image, mask, config)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/lama_cleaner/model/base.py", line 93, in __call__
    inpaint_result = self._pad_forward(image, mask, config)
  File "/usr/local/lib/python3.7/dist-packages/lama_cleaner/model/base.py", line 45, in _pad_forward
    result = self.forward(padd_image, padd_mask, config)
  File "/usr/local/lib/python3.7/dist-packages/torch/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/lama_cleaner/model/ldm.py", line 297, in forward
    steps=steps, conditioning=c, batch_size=c.shape[0], shape=shape
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/lama_cleaner/model/plms_sampler.py", line 85, in sample
    self.make_schedule(ddim_num_steps=steps, ddim_eta=eta, verbose=verbose)
  File "/usr/local/lib/python3.7/dist-packages/lama_cleaner/model/plms_sampler.py", line 41, in make_schedule
    eta=ddim_eta, verbose=verbose)
  File "/usr/local/lib/python3.7/dist-packages/lama_cleaner/model/utils.py", line 32, in make_ddim_sampling_parameters
    alphas = alphacums[ddim_timesteps]
IndexError: index 1000 is out of bounds for dimension 0 with size 1000

**Comment by DillFrescott** [comment]
Hmm, now it seems to be working. Very odd...
