### ISSUE TITLE
RuntimeError: The size of tensor a (2000) must match the size of tensor b (1336) at non-singleton dimension 3

### ISSUE THREAD

**Issue by 12ben** [Sanster/lama-cleaner#66]
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\lama_cleaner\server.py", line 115, in process
    res_np_img = model(image, mask, config)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\lama_cleaner\model_manager.py", line 37, in __call__
    return self.model(image, mask, config)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\lama_cleaner\model\base.py", line 98, in __call__
    inpaint_result = self._pad_forward(image, mask, config)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\lama_cleaner\model\base.py", line 51, in _pad_forward
    result = self.forward(pad_image, pad_mask, config)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\lama_cleaner\model\lama.py", line 63, in forward
    inpainted_image = self.model(image, mask)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/saicinpainting/training/trainers/default.py", line 11, in forward
    mask: Tensor) -> Tensor:
    _0 = self.generator
    masked_img = torch.mul(img, torch.rsub(mask, 1, 1))
                 ~~~~~~~~~ <--- HERE
    input = torch.cat([masked_img, mask], 1)
    _1 = torch.mul(mask, (_0).forward(input, ))

Traceback of TorchScript, original code (most recent call last):
/root/home/code/lama/saicinpainting/training/trainers/default.py(80): forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(860): _slow_forward
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py(887): _call_impl
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/jit/_trace.py(940): trace_module
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/torch/jit/_trace.py(742): trace
bin/to_jit.py(46): main
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/core/utils.py(160): run_job
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/_internal/hydra.py(105): run
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/_internal/utils.py(371): <lambda>
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/_internal/utils.py(211): run_and_report
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/_internal/utils.py(368): _run_hydra
/opt/venv/ocr-detection-detectron2/lib/python3.6/site-packages/hydra/main.py(53): decorated_main
bin/to_jit.py(59): <module>
RuntimeError: The size of tensor a (2000) must match the size of tensor b (1336) at non-singleton dimension 3

**Comment by Alekuso** [comment]
+1

**Comment by Sanster** [comment]
fixed in https://github.com/Sanster/lama-cleaner/releases/tag/0.32.1
