### ISSUE TITLE
Cannot switch to SD 1.4

### ISSUE THREAD

**Issue by Eidenz** [Sanster/lama-cleaner#72]
When attempting to switch to the new SD 1.4, it fails with the following log error:

```
127.0.0.1 - - [22/Sep/2022 17:16:37] "GET /model_downloaded/sd1.4 HTTP/1.1" 200 -
[2022-09-22 17:16:37,877] ERROR in app: Exception on /model [POST]
Traceback (most recent call last):
  File "C:\Users\eiden\anaconda3\lib\site-packages\huggingface_hub\utils\_errors.py", line 131, in _raise_for_status
    response.raise_for_status()
  File "C:\Users\eiden\anaconda3\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/CompVis/stable-diffusion-v1-4/revision/fp16

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\eiden\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\eiden\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\eiden\anaconda3\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\eiden\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\eiden\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\eiden\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\eiden\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\eiden\anaconda3\lib\site-packages\lama_cleaner\server.py", line 183, in switch_model
    model.switch(new_name)
  File "C:\Users\eiden\anaconda3\lib\site-packages\lama_cleaner\model_manager.py", line 39, in switch
    self.model = self.init_model(new_name, self.device, **self.kwargs)
  File "C:\Users\eiden\anaconda3\lib\site-packages\lama_cleaner\model_manager.py", line 21, in init_model
    model = models[name](device, **kwargs)
  File "C:\Users\eiden\anaconda3\lib\site-packages\lama_cleaner\model\base.py", line 24, in __init__
    self.init_model(device, **kwargs)
  File "C:\Users\eiden\anaconda3\lib\site-packages\lama_cleaner\model\sd.py", line 49, in init_model
    self.model = StableDiffusionInpaintPipeline.from_pretrained(
  File "C:\Users\eiden\anaconda3\lib\site-packages\diffusers\pipeline_utils.py", line 288, in from_pretrained
    cached_folder = snapshot_download(
  File "C:\Users\eiden\anaconda3\lib\site-packages\huggingface_hub\utils\_deprecation.py", line 93, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\eiden\anaconda3\lib\site-packages\huggingface_hub\_snapshot_download.py", line 168, in snapshot_download
    repo_info = _api.repo_info(
  File "C:\Users\eiden\anaconda3\lib\site-packages\huggingface_hub\hf_api.py", line 1454, in repo_info
    return self.model_info(
  File "C:\Users\eiden\anaconda3\lib\site-packages\huggingface_hub\hf_api.py", line 1276, in model_info
    _raise_for_status(r)
  File "C:\Users\eiden\anaconda3\lib\site-packages\huggingface_hub\utils\_errors.py", line 169, in _raise_for_status
    raise e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error: Repository Not Found for url: https://huggingface.co/api/models/CompVis/stable-diffusion-v1-4/revision/fp16. If the repo is private, make sure you are authenticated. (Request ID: O9i2-ve-nozMYbNTWMSms)
127.0.0.1 - - [22/Sep/2022 17:16:37] "POST /model HTTP/1.1" 500 -

```

**Comment by Eidenz** [comment]
The error might be due to login restriction from huggingface.co, as going on the link in a browser gives this:
```
{"id":"CompVis/stable-diffusion-v1-4","modelId":"CompVis/stable-diffusion-v1-4","author":"CompVis","sha":"a304b1ab1b59dd6c3ba9c40705c29c6de4144096","lastModified":"2022-08-22T16:05:41.000Z","private":false,"pipeline_tag":"text-to-image","tags":["diffusers","arxiv:2112.10752","arxiv:2103.00020","arxiv:2205.11487","arxiv:2207.12598","arxiv:1910.09700","stable-diffusion","stable-diffusion-diffusers","text-to-image","license:other"],"downloads":766423,"library_name":"diffusers","likes":1235,"model-index":null,"cardData":{"license":"other","tags":["stable-diffusion","stable-diffusion-diffusers","text-to-image"],"inference":false,"extra_gated_prompt":"One more step before getting this model\nThis model is open access and available to all, but it has the CreativeML OpenRAIL-M license you have to be aware of before using it - don't worry you are just one click away! \nBy clicking on \"Access repository\" below, you accept that your *contact information* (email address and username) can be shared with the model authors as well.\nSummary of the CreativeML OpenRAIL License: \n1. You can't use the model to deliberately produce nor share illegal or harmful outputs or content \n2. We claim no rights on the outputs you generate, you are free to use them and are accountable for their use which should not go against the provisions set in the license\n3. You may re-distribute the weights and use the model commercially and/or as a service. If you do, please be aware you have to include the same use restrictions as the ones in the license and share a copy of the CreativeML OpenRAIL-M to all your users (please read the license entirely and carefully)\nPlease read the full license here: https://huggingface.co/spaces/CompVis/stable-diffusion-license\n  ","extra_gated_fields":{"I have read the License and agree with its terms":"checkbox"}},"siblings":[{"rfilename":".gitattributes"},{"rfilename":"README.md"},{"rfilename":"feature_extractor/preprocessor_config.json"},{"rfilename":"model_index.json"},{"rfilename":"safety_checker/config.json"},{"rfilename":"safety_checker/pytorch_model.bin"},{"rfilename":"scheduler/.ipynb_checkpoints/scheduler_config-checkpoint.json"},{"rfilename":"scheduler/scheduler_config.json"},{"rfilename":"text_encoder/config.json"},{"rfilename":"text_encoder/pytorch_model.bin"},{"rfilename":"tokenizer/merges.txt"},{"rfilename":"tokenizer/special_tokens_map.json"},{"rfilename":"tokenizer/tokenizer_config.json"},{"rfilename":"tokenizer/vocab.json"},{"rfilename":"unet/config.json"},{"rfilename":"unet/diffusion_pytorch_model.bin"},{"rfilename":"v1-variants-scores.jpg"},{"rfilename":"vae/config.json"},{"rfilename":"vae/diffusion_pytorch_model.bin"}]}
```

with this sentence explaining it: `One more step before getting this model\nThis model is open access and available to all, but it has the CreativeML OpenRAIL-M license you have to be aware of before using it - don't worry you are just one click away!`

**Comment by Eidenz** [comment]
It seems my hf_access_token was wrong, as entering it again fixed it. Might still be a good idea to show how to put the model manually like the other methods.

**Comment by N-Upchurch** [comment]
How did you install this model? I'm having the same problem.
